// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionInfo } from "./CollectionInfo";
import type { VideoInfo } from "./VideoInfo";

/**
 * Resultado de `analyze`: vídeo ou coleção.
 */
export type Analysis = { "type": "video", info: VideoInfo, } | { "type": "collection", info: CollectionInfo, };
