// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Informações básicas do app enviadas à UI (`app_info`).
 */
export type AppInfo = { version: string, platform: string, arch: string, };
