// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedTrack } from "./ImportedTrack";

export type ArtistRelease = { artistId: string, id: string, title: string, recordType: string, releaseDate: string | null, cover: string | null, monitored: boolean, tracks: Array<ImportedTrack>, present: number, total: number, state: string, };
