// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistOptions = { monitorExisting: string, monitorNew: string, types: Array<string>, excludeVariants: boolean, profileId: string, outputDir: string | null, };
