// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistHit = { id: string, name: string, picture: string | null, fans: number, };
