// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Formato só de áudio (sem vídeo e com codec de áudio conhecido).
 */
export type AudioFormat = { formatId: string, acodec: string, abr: number | null, ext: string, };
