// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O que fazer com o resultado: aplicar sozinho, mandar para revisão ou nada.
 */
export type Bucket = "auto" | "review" | "none";
