// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um possível casamento devolvido por um provedor.
 */
export type Candidate = { provider: string, providerId: string, title: string, artists: Array<string>, album: string | null, albumArtist: string | null, year: number | null, genre: string | null, trackNo: number | null, trackTotal: number | null, discNo: number | null, durationS: number | null, coverUrl: string | null, mbRecordingId: string | null, isrc: string | null, };
