// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionEntry } from "./CollectionEntry";

export type CollectionInfo = { id: string | null, title: string | null, channel: string | null, entries: Array<CollectionEntry>, };
