// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Formato serializado de `CoreError` (o que a UI recebe como erro de comando).
 */
export type CoreError = { kind: string, message: string, i18nKey?: string, };
