// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticItem } from "./DiagnosticItem";

export type DiagnosticReport = { createdAt: number, items: Array<DiagnosticItem>, };
