// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticLevel } from "./DiagnosticLevel";

export type DiagnosticItem = { id: string, level: DiagnosticLevel, detail: string, };
