// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dados finais do download (`--print after_move:`).
 */
export type DoneInfo = { id: string, title: string, filepath: string, ext: string, abr: number | null, acodec: string | null, formatId: string | null, duration: number | null, };
