// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobOptions } from "./JobOptions";
import type { PlaylistCtx } from "./PlaylistCtx";

/**
 * Pedido para enfileirar (comando `enqueue`).
 */
export type EnqueueRequest = { url: string, sourceId?: string, title?: string, thumbnail?: string, durationS?: number, profileId?: string, options?: JobOptions, metadataOverride: Record<string, unknown> | null, playlistCtx?: PlaylistCtx, 
/**
 * "Baixar agora": entra na frente da fila.
 */
priority: boolean, allowDuplicate: boolean, };
