// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorKind = "cancelled" | "unavailable" | "age_restricted" | "bot_check" | "geo_blocked" | "disk" | "ffmpeg" | "extractor" | "network" | "unknown";
