// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtistOptions } from "./ArtistOptions";

export type FollowedArtist = { id: string, providerArtistId: string, name: string, picture: string | null, options: ArtistOptions, lastCheckAt: number | null, };
