// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataFields } from "./MetadataFields";

export type ImportedTrack = { id: string, fields: MetadataFields, durationS: number | null, isrc: string | null, explicit: boolean | null, };
