// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncCreate } from "./SyncCreate";

export type ImportSelection = { url: string, trackIds: Array<string>, mode: string, profileId: string, syncOptions: SyncCreate | null, };
