// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedTrack } from "./ImportedTrack";
import type { MatchResult } from "./MatchResult";

export type ImportedItem = { track: ImportedTrack, matched: MatchResult, };
