// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedTrack } from "./ImportedTrack";

export type ImportedCollection = { provider: string, id: string, url: string, title: string, cover: string | null, tracks: Array<ImportedTrack>, checksum: string | null, };
