// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFailure } from "./ImportFailure";

export type ImportReport = { imported: number, skipped: number, failures: Array<ImportFailure>, };
