// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedCollection } from "./ImportedCollection";
import type { ImportedItem } from "./ImportedItem";

export type ImportAnalysis = { collection: ImportedCollection, items: Array<ImportedItem>, };
