// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobOptions } from "./JobOptions";
import type { JobStage } from "./JobStage";
import type { JobStatus } from "./JobStatus";
import type { PlaylistCtx } from "./PlaylistCtx";

export type Job = { id: string, kind: string, provider: string, sourceUrl: string, sourceId: string | null, title: string | null, artist: string | null, thumbnail: string | null, durationS: number | null, profileId: string, options: JobOptions, metadataOverride: Record<string, unknown> | null, warnings: Array<string>, playlistCtx: PlaylistCtx | null, syncId: string | null, status: JobStatus, stage: JobStage, 
/**
 * Progresso do estágio atual (0–1).
 */
progress: number, 
/**
 * Progresso geral ponderado (0–1), monotônico.
 */
overallProgress: number, speedBps: number | null, etaS: number | null, errorKind: string | null, errorMessage: string | null, attempts: number, outputPath: string | null, libraryId: number | null, position: number, createdAt: number, updatedAt: number, finishedAt: number | null, };
