// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sobrescritas por job das configurações globais (todas opcionais).
 */
export type JobOptions = { fetchMetadata?: boolean, fetchLyrics?: boolean, fetchArtwork?: boolean, sponsorblock?: boolean, autoOrganize?: boolean, outputDir?: string, splitChapters?: boolean, };
