// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobStage = "waiting" | "waiting_retry" | "analyzing" | "downloading" | "converting" | "metadata" | "artwork" | "lyrics" | "loudness" | "tagging" | "moving" | "done";
