// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryDateRange } from "./LibraryDateRange";
import type { LibrarySort } from "./LibrarySort";

export type LibraryQuery = { text: string | null, artist: string | null, album: string | null, format: string | null, dateRange: LibraryDateRange, needsReview: boolean | null, missing: boolean | null, sort: LibrarySort, offset: number, limit: number, };
