// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";
import type { ScoredCandidate } from "./ScoredCandidate";

/**
 * Espelho da tabela `library`; inclui os campos reservados para importação e reexame.
 */
export type LibraryItem = { id: number, filePath: string, missing: boolean, provider: string | null, sourceId: string | null, sourceUrl: string | null, isrc: string | null, title: string, artist: string | null, album: string | null, albumArtist: string | null, trackNo: number | null, trackTotal: number | null, discNo: number | null, year: number | null, genre: string | null, durationS: number | null, codec: string | null, bitrateKbps: number | null, sourceAbrKbps: number | null, profileId: string | null, contentType: ContentType, metadataSource: string | null, confidence: number | null, needsReview: boolean, reviewCandidates: Array<ScoredCandidate> | null, hasLyrics: boolean, hasSyncedLyrics: boolean, coverSource: string | null, acoustidId: string | null, mbRecordingId: string | null, replaygainDb: number | null, losslessVerdict: string | null, origin: string, addedAt: number, updatedAt: number, };
