// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LosslessVerdict } from "./LosslessVerdict";

export type LosslessReport = { verdict: LosslessVerdict, details: string, spectrogramPngBase64: string, rmsDb: number, high16Db: number, high19Db: number, };
