// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bucket } from "./Bucket";
import type { ContentType } from "./ContentType";
import type { MetadataFields } from "./MetadataFields";
import type { OfficialMatch } from "./OfficialMatch";
import type { ScoredCandidate } from "./ScoredCandidate";

/**
 * Resultado da identificação (gravado em `jobs.metadata_result_json`).
 */
export type MetadataResult = { fields: MetadataFields, 
/**
 * 0–1. `1.0` para faixa oficial do YouTube Music e para edição do usuário.
 */
confidence: number, 
/**
 * `youtube_music`, `youtube`, `deezer`, `itunes`, `musicbrainz` ou `user`.
 */
source: string, bucket: Bucket, 
/**
 * Até 5, do melhor para o pior (só quando há o que revisar).
 */
candidates: Array<ScoredCandidate>, contentType: ContentType, isrc: string | null, 
/**
 * Versão oficial encontrada para o vídeo (trocada ou apenas sugerida).
 */
official: OfficialMatch | null, };
