// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Campos finais de uma faixa (o que o F09 grava nas tags).
 */
export type MetadataFields = { title: string, 
/**
 * Texto de exibição (`A`, `A feat. B`, `A, B`).
 */
artist: string | null, artists: Array<string>, album: string | null, albumArtist: string | null, year: number | null, genre: string | null, trackNo: number | null, trackTotal: number | null, discNo: number | null, coverUrl: string | null, mbRecordingId: string | null, };
