// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Onde colocar um job reordenado.
 */
export type MoveTarget = { "before": string } | { "after": string } | "front" | "back";
