// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfficialVia } from "./OfficialVia";

/**
 * A faixa oficial encontrada para um vídeo.
 */
export type OfficialMatch = { videoId: string, url: string, score: number, title: string, artist: string, album: string | null, isrc: string | null, via: OfficialVia, };
