// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De onde o job veio, quando é item de uma playlist/álbum.
 */
export type PlaylistCtx = { playlistTitle: string, playlistId: string, index: number, syncId?: string, };
