// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoInfo } from "./VideoInfo";

/**
 * Pedido de `metadata_preview`: a URL (e, se a UI já tiver, a análise do vídeo, que poupa uma
 * chamada ao yt-dlp).
 */
export type PreviewRequest = { url: string, video?: VideoInfo, 
/**
 * Simula com a versão oficial (`true`), sem ela (`false`) ou como as configurações (`None`).
 */
useOfficial?: boolean, };
