// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O que o ffprobe diz do primeiro stream de áudio.
 */
export type ProbeInfo = { codec: string, bitrateKbps: number | null, durationS: number, sampleRate: number | null, channels: number | null, };
