// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Versão serializável para a UI.
 */
export type ProfileInfo = { id: string, i18nKey: string, ext: string, reencodes: boolean, };
