// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progresso do download. Sem `total` o progresso é indeterminado.
 */
export type ProgressUpdate = { downloaded: number, total: number | null, 
/**
 * Bytes por segundo.
 */
speed: number | null, 
/**
 * Segundos restantes.
 */
eta: number | null, 
/**
 * `status == "finished"` do yt-dlp (o fim real do job é o `REVERB_DONE`).
 */
finished: boolean, };
