// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item de busca (modo `--flat-playlist`: a duração só existe no `ytsearch`, não no YouTube Music).
 */
export type SearchResult = { id: string, title: string, url: string | null, duration: number | null, channel: string | null, };
