// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quais chaves opcionais estão preenchidas (a UI nunca recebe os valores).
 */
export type SecretsStatus = { acoustid: boolean, spotify: boolean, discogs: boolean, jamendo: boolean, };
