// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookiesSource } from "./CookiesSource";
import type { JsRuntime } from "./JsRuntime";
import type { Language } from "./Language";
import type { PotProvider } from "./PotProvider";
import type { SecretsStatus } from "./SecretsStatus";
import type { SplitChapters } from "./SplitChapters";
import type { Theme } from "./Theme";
import type { Transparency } from "./Transparency";
import type { YtdlpChannel } from "./YtdlpChannel";

/**
 * O que a UI recebe: todos os campos menos os segredos, mais `secretsStatus`.
 */
export type SettingsView = { outputDir: string, fileTemplate: string, autoOrganize: boolean, defaultProfile: string, parallelism: number, speedLimitMbps: number, queueLimit: number, maxAttempts: number, fetchMetadata: boolean, extractTitleFromVideo: boolean, preferOfficialAudio: boolean, confidenceAutoApply: number, confidenceReview: number, offlineMode: boolean, fetchArtwork: boolean, writeFolderCover: boolean, fetchLyrics: boolean, writeLrcFile: boolean, normalizeVolume: boolean, sponsorblockRemove: boolean, sponsorblockCategories: Array<string>, splitChapters: SplitChapters, trimSilence: boolean, playlistPacingSeconds: number, watchLibrary: boolean, theme: Theme, language: Language, transparency: Transparency, launchAtStartup: boolean, startMinimized: boolean, minimizeToTray: boolean, closeToTray: boolean, completionNotifications: boolean, clipboardWatch: boolean, globalShortcut: string, weeklySelfTest: boolean, onboardingCompleted: boolean, cookiesSource: CookiesSource, cookiesFile: string, ytdlpChannel: YtdlpChannel, jsRuntime: JsRuntime, autoUpdateTools: boolean, potProvider: PotProvider, qualityTargetKbps: number, autoUpgrade: boolean, artistCheckIntervalHours: number, autoCheckAppUpdates: boolean, verifyLosslessOnImport: boolean, secretsStatus: SecretsStatus, };
