// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncResult } from "./SyncResult";

export type Sync = { id: string, provider: string, url: string, playlistId: string | null, title: string, thumbnail: string | null, profileId: string, outputDir: string | null, intervalHours: number, maxItems: number | null, removeDeleted: boolean, writeM3u: boolean, enabled: boolean, lastSyncAt: number | null, lastResult: SyncResult | null, createdAt: number, itemCount: number, };
