// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncItem = { syncId: string, sourceId: string, position: number, title: string | null, state: string, jobId: string | null, libraryId: number | null, jobStatus: string | null, filePath: string | null, missing: boolean, };
