// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncResult = { checksum: string | null, added: number, removed: number, failed: number, duplicates: Array<string>, unavailable: number, running: boolean, error: string | null, };
