// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedEntry } from "./PlannedEntry";

export type SyncPlan = { add: Array<PlannedEntry>, removed: Array<string>, reordered: Array<PlannedEntry>, unchanged: Array<PlannedEntry>, duplicates: Array<string>, unavailable: number, };
