// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncUpdate = { title: string, profileId: string, outputDir: string | null, intervalHours: number, maxItems: number | null, removeDeleted: boolean, writeM3u: boolean, enabled: boolean, };
