// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolPhase = "downloading" | "verifying" | "extracting" | "installing_deps" | "testing" | "waiting_jobs";
