// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";

export type ToolStatus = { tool: Tool, 
/**
 * Ferramenta indispensável para baixar (yt-dlp, FFmpeg).
 */
required: boolean, installed: boolean, version: string | null, previousVersion: string | null, channel: string | null, installedAt: string | null, path: string | null, 
/**
 * Última versão conhecida (da última verificação de atualizações).
 */
latestVersion: string | null, updateAvailable: boolean, lastChecked: string | null, };
