// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";
import type { ToolPhase } from "./ToolPhase";

/**
 * Payload de `tools://progress`.
 */
export type ToolProgress = { tool: Tool, phase: ToolPhase, percent: number, };
