// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";

/**
 * Payload de `tools://changed`.
 */
export type ToolChanged = { tool: Tool, version: string | null, };
