// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCover } from "./TagCover";

/**
 * Representação comum aos quatro formatos e ao editor da F10. `None` remove o campo.
 */
export type TrackTags = { title: string, artist: string | null, album: string | null, albumArtist: string | null, year: number | null, trackNo: number | null, trackTotal: number | null, discNo: number | null, genre: string | null, lyrics: string | null, comment: string | null, isrc: string | null, cover: TagCover | null, replayGainTrackGain: string | null, replayGainTrackPeak: string | null, 
/**
 * Somente Opus: ganho em unidades de 1/256 dB relativo a -23 LUFS.
 */
r128TrackGain: number | null, };
