// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryItem } from "./LibraryItem";

export type UpgradeCandidate = { item: LibraryItem, availableAbrKbps: number, };
