// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resultado de `classify`. `url` é sempre a forma normalizada que o yt-dlp deve receber.
 */
export type UrlKind = { "kind": "video", sourceId: string, url: string, playlistHint: boolean, } | { "kind": "collection", url: string, } | { "kind": "search", query: string, } | { "kind": "unsupported" };
