// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFormat } from "./AudioFormat";
import type { Chapter } from "./Chapter";
import type { Thumbnail } from "./Thumbnail";

export type VideoInfo = { id: string, title: string, duration: number | null, channel: string | null, uploader: string | null, thumbnail: string | null, thumbnails: Array<Thumbnail>, categories: Array<string>, track: string | null, artist: string | null, artists: Array<string>, creators: Array<string>, album: string | null, releaseYear: number | null, releaseDate: string | null, chapters: Array<Chapter>, audioFormats: Array<AudioFormat>, 
/**
 * Maior `abr` entre os formatos de áudio; `None` se nenhum informar.
 */
bestAudioAbr: number | null, 
/**
 * `track` presente e artista conhecido: metadado oficial do YouTube Music.
 */
isOfficialTrack: boolean, webpageUrl: string | null, extractorKey: string | null, };
